---

exclude:
    - '^(.*)[\/\\\\]project[\/\\\\]pycryptobot[\/\\\\]templates[\/\\\\](.*)$'

ignore:
    - '^(.*)pyc(.*)$'
    - '^(.*)pyo(.*)$'
    - '^(.*)__pycache__(.*)$'

variables:
    -   name: label
        prompt: "App Label"
        case: "lower"
        default: "pycryptobot"

    -   name: name
        prompt: "App Name"
        default: "PyCryptoBot"

    -   name: class_name
        prompt: "App Class Name"
        validate: "^[a-zA-Z0-9]+$"
        default: "PyCryptoBot"

    -   name: description
        prompt: "App Description"
        default: "Python Crypto Bot consuming Coinbase Pro or Binance APIs"

    -   name: creator
        prompt: "Creator Name"
        default: "Michael Whittle"

    -   name: creator_email
        prompt: "Creator Email"
        default: "john.doe@example.com"

    -   name: url
        prompt: "Project URL"
        default: "https://github.com/whittlem/pycryptobot"

    -   name: license
        prompt: "License"
        default: " Apache-2.0 License"
